---
- hosts: all
  vars:
    - var1: "Varibale 1"
  tasks:
    - name: echo stuff
      command: echo -e " {{ var1 }} 1\n{{ var1 }} 2" 
      register: results

    - name: module debug
      debug: msg=" {{ results.stdout_lines }} "