---
- hosts: all
  become: true
  tasks:
    - name: get username
      shell: uname > /home/ansible-master/results.txt
    - name: who am i
      shell: whoami >> /home/ansible-master/results.txt

    - name: testing raw modules
      raw: echo "hi" >> /home/ansible-master/results.txt