---
- hosts: all
  become: true
  tasks:
    - name: install vsftpd
      yum: name=vsftpd state=latest update_cache=yes 
      ignore_errors: yes # ignores errors if any errors found in yaml, if this nto set, it will stop execution if error found, otherwise keep executing even though an error found

      # handler 
      notify: start vsftpd
  
  handlers: 
    - name: start vsftpd
      service: name=vsftpd enabled=true state=started