---
- hosts: all
  become: yes
  tasks:
    - name: install httpd using apt
      apt: name=httpd state=present
      when: ansible_os_family == "Debian"

    - name: install httpd using yum
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"