---
- hosts: all
  become: yes
  tasks:
    - name: install httpd
      apt: name=httpd state=latest
      when: ansible_os_family == 'Debian'

    - name: install httpd
      yum: name=httpd state=latest
      when: ansible_os_family = 'RedHat'