---
- hosts: all
  become: yes
  vars:
    file_version: 1.0
  tasks:
    - name: install index file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0777