---
- include: update-system-playbook.yaml

- hosts: all
  become: yes
  tasks:
    - include: install-httpd-task.yaml
  handlers:
    - name: start-httpd
      service: name=httpd state=started enabled=yes